import './style.css';
import {COURSES,createRace,stepRace,position,formatTime,mod,BOOST_COST,BOOST_DURATION} from './game.js';
import {createTrack} from './track.js';
import {RaceScene} from './scene.js';
import {bindRaceSteering} from './legacy/race-controls.js';
import {OceanAudio} from './audio.js';
const $=s=>document.querySelector(s);const audio=new OceanAudio();let course=COURSES[0],track=createTrack(course),race=createRace({track,length:track.length,course}),scene,menu=true,quality='high',lastEvent=null,noticeUntil=0,pausedFrom='racing',frameTime=0,last=performance.now(),lastHud=0;
const keys=new Set(),held=new Map();let steering,jumpQueued=false,boostQueued=false;
function records(){try{const p=JSON.parse(localStorage.getItem('blue-rush.records.v1')||'{}');return p&&typeof p==='object'?p:{};}catch{return {};}}
function recordText(){const r=records()[course.id];$('#record').textContent=r&&Number.isFinite(r.time)?`나의 최고 기록 ${formatTime(r.time)}`:'첫 기록을 남겨 보세요';}
function choose(id){course=COURSES.find(c=>c.id===id)||COURSES[0];track=createTrack(course);race=createRace({track,length:track.length,course});scene?.setTrack(track,course);scene?.setObjects(race.objects);document.querySelectorAll('.course').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===id)));$('#course-description').textContent=course.description;recordText();drawMap();}
$('#courses').innerHTML=COURSES.map((c,i)=>`<button class="course" data-id="${c.id}" aria-pressed="${i===0}"><span class="course-marker">${['≈','◌','☀'][i]}</span><span><strong>${c.name}</strong><small>${c.tag}</small></span><span class="difficulty">${c.difficulty}</span></button>`).join('');
$('#courses').addEventListener('click',e=>{const b=e.target.closest('.course');if(b)choose(b.dataset.id);});
function clearInput(){race.throttle=false;jumpQueued=false;boostQueued=false;keys.clear();held.clear();steering?.reset();document.querySelectorAll('.held').forEach(b=>b.classList.remove('held'));}
function closeDialogs(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());}
function start(){if(!scene)return;closeDialogs();clearInput();menu=false;lastEvent=null;noticeUntil=0;$('#notice').textContent='';$('#notice').classList.remove('show');race=createRace({track,length:track.length,course,seed:crypto.getRandomValues(new Uint32Array(1))[0]});scene.setObjects(race.objects);scene.foam.reset();scene.history=[];scene.snap=true;$('#menu').hidden=true;$('#scene-caption').hidden=true;$('#hud').hidden=false;$('#pause').hidden=false;document.body.classList.add('playing');$('#course-label').textContent=course.name;scene.renderer.domElement.focus();}
function showMenu(){closeDialogs();clearInput();menu=true;race.phase='menu';$('#menu').hidden=false;$('#scene-caption').hidden=false;$('#hud').hidden=true;$('#pause').hidden=true;document.body.classList.remove('playing');scene.snap=true;recordText();$('#start').focus();}
function pause(){if(menu||!['racing','countdown'].includes(race.phase))return;pausedFrom=race.phase;race.phase='paused';clearInput();$('#pause-dialog').showModal();audio.update(0,false,false);}
function resume(){if(race.phase!=='paused')return;$('#pause-dialog').close();clearInput();race.phase=pausedFrom;scene.renderer.domElement.focus();last=performance.now();}
$('#start').onclick=start;$('#pause').onclick=pause;$('#resume').onclick=resume;$('#restart').onclick=start;$('#back-menu').onclick=showMenu;$('#again').onclick=start;$('#result-menu').onclick=showMenu;
$('#pause-dialog').addEventListener('cancel',e=>{e.preventDefault();resume();});$('#result-dialog').addEventListener('cancel',e=>{e.preventDefault();showMenu();});
$('#help').onclick=()=>$('#help-dialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#help-dialog').close());
$('#sound').onclick=async()=>{try{if(audio.enabled)audio.disable();else await audio.enable();$('#sound').textContent=audio.enabled?'소리 켜짐':'소리 꺼짐';$('#sound').setAttribute('aria-label',audio.enabled?'소리 끄기':'소리 켜기');$('#sound').setAttribute('aria-pressed',String(audio.enabled));}catch{$('#sound').textContent='소리 사용 불가';}};
$('#quality').onclick=()=>{quality=quality==='high'?'low':'high';scene?.setQuality(quality);$('#quality').textContent=quality==='high'?'그래픽 높음':'그래픽 가벼움';};
steering=bindRaceSteering([$('#left'),$('#right')],()=>{},()=>!menu&&race.phase==='racing');
for(const name of ['jump','drift','brake','boost','throttle']){const b=$('#'+name);b.onpointerdown=e=>{if(e.button>0||menu||race.phase!=='racing')return;e.preventDefault();b.setPointerCapture(e.pointerId);held.set(e.pointerId,name);if(name==='jump')jumpQueued=true;if(name==='boost')boostQueued=true;b.classList.add('held');};for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,e=>{held.delete(e.pointerId);b.classList.toggle('held',[...held.values()].includes(name));});b.oncontextmenu=e=>e.preventDefault();b.addEventListener('keydown',e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();e.stopPropagation();held.set(`key-${name}`,name);if(name==='jump'&&!e.repeat)jumpQueued=true;if(name==='boost'&&!e.repeat)boostQueued=true;}});b.addEventListener('keyup',e=>{if([' ','Enter'].includes(e.key))held.delete(`key-${name}`);});b.addEventListener('blur',()=>held.delete(`key-${name}`));b.addEventListener('click',e=>{if(e.detail===0&&!menu&&race.phase==='racing'){held.set(`accessible-${name}`,name);if(name==='boost')boostQueued=true;setTimeout(()=>held.delete(`accessible-${name}`),name==='drift'?850:150);}});}
const controlKeys=['ArrowLeft','ArrowRight','ArrowDown','KeyE','ArrowUp','KeyW','KeyA','KeyD','KeyS','Space','ShiftLeft','ShiftRight'];
addEventListener('keydown',e=>{if(e.code==='Escape'){if(race.phase==='paused')resume();else pause();return;}if(controlKeys.includes(e.code)&&!menu&&!document.querySelector('dialog[open]')&&!(e.code==='Space'&&document.activeElement?.tagName==='BUTTON')){e.preventDefault();keys.add(e.code);if(e.code==='Space'&&!e.repeat)jumpQueued=true;if(e.code==='KeyE'&&!e.repeat)boostQueued=true;}});
addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{clearInput();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();pause();}});
function input(){const actions=[...held.values()],queued=jumpQueued,boostTap=boostQueued;jumpQueued=false;boostQueued=false;return {boost:boostTap||keys.has('KeyE')||actions.includes('boost'),throttle:keys.has('ArrowUp')||keys.has('KeyW')||actions.includes('throttle'),steer:Math.max(-1,Math.min(1,(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0)+steering.value)),jump:queued||keys.has('Space')||actions.includes('jump'),drift:keys.has('ShiftLeft')||keys.has('ShiftRight')||actions.includes('drift'),brake:keys.has('ArrowDown')||keys.has('KeyS')||actions.includes('brake')};}
function finish(){clearInput();const all=records(),old=all[course.id],isBest=!old||!Number.isFinite(old.time)||race.time<old.time;let saved=true;if(isBest){all[course.id]={time:race.time,date:new Date().toISOString(),rank:race.rank};try{localStorage.setItem('blue-rush.records.v1',JSON.stringify(all));}catch{saved=false;}}
 $('#result-kicker').textContent=`${course.name} · ${race.rank}위 / 4명`;$('#result-title').textContent=race.rank===1?'바다의 가장 빠른 물결.':'세 바퀴, 끝까지 해냈어요.';$('#result-time').textContent=formatTime(race.time);$('#result-record').textContent=!saved?'브라우저 저장 공간에 기록을 저장하지 못했어요.':isBest?'나의 최고 기록을 새로 썼어요!':`나의 최고 기록 ${formatTime(old.time)}`;
 $('#result-stats').innerHTML=`<span>가장 빠른 바퀴<strong>${formatTime(race.bestLap)}</strong></span><span>획득 아이템<strong>${race.pickups}개</strong></span><span>회피 성공<strong>${race.dodges}회</strong></span><span>부스터 가속<strong>${race.boosts}회</strong></span>`;$('#result-dialog').showModal();}
function drawMap(){const canvas=$('#minimap'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const points=track.curve.getSpacedPoints(180),xs=points.map(p=>p.x),zs=points.map(p=>p.z),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),scale=Math.min((w-36)/(maxX-minX),(h-30)/(maxZ-minZ));const project=p=>[w/2+(p.x-(minX+maxX)/2)*scale,h/2+(p.z-(minZ+maxZ)/2)*scale];ctx.lineWidth=7;ctx.strokeStyle='#78c4c554';ctx.beginPath();points.forEach((p,i)=>{const q=project(p);i?ctx.lineTo(...q):ctx.moveTo(...q);});ctx.stroke();ctx.lineWidth=2;ctx.strokeStyle='#b2efe1';ctx.stroke();if(!menu)for(const r of race.rivals){const q=project(track.sample(r.distance).p);ctx.fillStyle='#e9c19a';ctx.beginPath();ctx.arc(...q,3,0,Math.PI*2);ctx.fill();}const p=project(track.sample(menu?0:race.distance).p);ctx.fillStyle='#fbfff1';ctx.beginPath();ctx.arc(...p,5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#073d4c';ctx.lineWidth=2;ctx.stroke();}
function hud(info){$('#lap').innerHTML=`${Math.min(race.laps,Math.floor(race.distance/race.length)+1)}<small> / ${race.laps}</small>`;$('#rank').textContent=position(race);$('#speed').textContent=Math.round(race.speed*3.6);$('#time').textContent=formatTime(race.time);$('#zone').textContent=info.under?`수심 ${Math.round(info.depth)} m`:'수면 · 윤슬 구간';$('#progress').style.width=`${race.distance/(race.length*race.laps)*100}%`;$('#countdown').textContent=race.phase==='countdown'?Math.max(1,Math.ceil(race.countdown)):'';$('#drift-fill').style.width=`${race.drift/2.2*100}%`;
 const effect=race.slow>0?['먹물 / 충돌 감속',race.slow/2.8,'#e5a9de']:race.boost>0?['해류 부스트',race.boost/BOOST_DURATION,'#9effdd']:race.shield>0?['버블 실드',race.shield/9,'#b7d9ff']:race.drift>0?[race.drift>=.65?'놓으면 부스터 충전!':'드리프트 충전',race.drift/2.2,'#ffe0a0']:['',0,'#9effdd'];$('#effect-label').textContent=effect[0];$('#effect-fill').style.width=`${Math.min(1,effect[1])*100}%`;$('#effect-fill').style.background=effect[2];$('#effect').style.opacity=effect[0]?1:0;$('#drive-state').textContent=race.slow>0?'감속 중':race.boost>0?'부스트 가속':race.wasDrift?'드리프트':race.throttle?'엑셀 · 가속 중':'↑ / W 누르고 가속';
 $('#throttle').classList.toggle('held',race.throttle);$('#throttle').setAttribute('aria-pressed',String(race.throttle));
 $('#throttle-status').textContent=race.throttle?'가속 중':'누르고 가속';$('#throttle-fill').style.width=`${race.throttle?Math.min(100,race.speed/(race.course.speed*1.5)*100):0}%`;
 const boosting=race.boost>0,canBoost=race.energy>=BOOST_COST;
 $('#boost-fill').style.width=`${race.energy}%`;$('#boost-status').textContent=boosting?'가속 중':`${Math.round(race.energy)} / 100`;
 $('#boost').classList.toggle('ready',canBoost);$('#boost').classList.toggle('boosting',boosting);$('#boost').setAttribute('aria-pressed',String(boosting));
 $('#boost').setAttribute('aria-label',`부스터 · 잔량 ${Math.round(race.energy)} / 100 · 한 번에 25 사용${canBoost?' · 사용 가능':''}`);
 const event=race.events.at(-1);if(event&&event!==lastEvent){lastEvent=event;if(event.type!=='jump'){$('#notice').textContent=event.text;noticeUntil=frameTime+2.1;}audio.cue(event.type);}$('#notice').classList.toggle('show',frameTime<noticeUntil);drawMap();
 Object.assign(scene.renderer.domElement.dataset,{phase:race.phase,throttle:String(race.throttle),speed:race.speed.toFixed(2),jump:race.jump.toFixed(2),distance:race.distance.toFixed(2),x:race.x.toFixed(2),underwater:String(info.under),boost:race.boost.toFixed(2),energy:String(race.energy),hits:String(race.hits),dodges:String(race.dodges),boosts:String(race.boosts),drift:race.drift.toFixed(2),drawCalls:String(info.drawCalls),rider:'aqua-bike',visibleRivals:String(info.visibleRivals),immersion:info.immersion.toFixed(2),audioSurface:audio.mix.surface.toFixed(3),audioUnderwater:audio.mix.underwater.toFixed(3),audioBubbles:audio.mix.bubbles.toFixed(3)});
}
try{scene=new RaceScene($('#world'),track,course);scene.setObjects(race.objects);choose(course.id);}catch(e){console.error(e);$('#error').hidden=false;$('#start').disabled=true;}
function loop(now){requestAnimationFrame(loop);if(!scene)return;const dt=Math.min(.05,(now-last)/1000);last=now;const active=!document.hidden&&race.phase!=='paused'&&race.phase!=='finished';if(active&&(!menu||!scene.reduced))frameTime+=dt;const previous=race.phase;if(!menu){race.visualTime=frameTime;stepRace(race,input(),dt);}if(previous!=='finished'&&race.phase==='finished')finish();
 const info=scene.update(race,frameTime,dt,{menu,quality});audio.update(race.speed,info.immersion,!menu&&race.phase==='racing');if(now-lastHud>65){lastHud=now;if(!menu)hud(info);}}
requestAnimationFrame(loop);
// Read-only diagnostics; no mutable test controls or shortcuts in production.
Object.defineProperty(window,'blueRush',{get:()=>({phase:race.phase,course:course.id,distance:race.distance,length:race.length,speed:race.speed,jump:race.jump,x:race.x,boost:race.boost,energy:race.energy,dodges:race.dodges,hits:race.hits,boosts:race.boosts,slow:race.slow,drifts:race.drifts,jumps:race.jumps,pickups:race.pickups,underwater:scene?.craft.position.y< -3,time:race.time})});
